#!/bin/sh
# tests/test-create.sh — environments/create.sh. The interesting output is the
# cloud-init seed: it is generated by string concatenation, so every test here
# parses the result as real YAML rather than grepping hopefully.
set -u
. "$(dirname "$0")/lib.sh"
. "$(dirname "$0")/harness.sh"

echo "== environments/create.sh =="

# Recover the user-data from the seed ISO (create.sh shreds the staging copy on
# purpose — the plaintext password must not survive next to the ISO).
extract_userdata() {
  iso="$1"; out="$2"
  xorriso -osirrox on -indev "$iso" -extract /user-data "$out" >/dev/null 2>&1 \
    || xorriso -osirrox on -indev "$iso" -extract /user_data "$out" >/dev/null 2>&1
  [ -s "$out" ]
}
yaml_ok() { python3 -c 'import sys,yaml; yaml.safe_load(open(sys.argv[1]))' "$1"; }

new_sandbox
"$SANDBOX/environments/create.sh" > "$SANDBOX/create.out" 2>&1
create_rc=$?
assert_eq "create.sh completes for the default three-env config" 0 "$create_rc"

# --- one VM per enabled env, each on its own isolated network ----------------
for e in office development administration; do
  assert_contains "virt-install ran for $e" "$STUB_LOG" "virt-install .*--name $e "
  assert_contains "$e is attached to its own network" "$STUB_LOG" "--network network=isol-$e,"
  assert_contains "$e is set to autostart" "$STUB_LOG" "virsh autostart $e"
done
assert_contains "each env's network is defined with its own bridge" "$SANDBOX/stub-state/netxml-isol-development" "<bridge name='virbr2'"
assert_contains "each env's network gets its own /24" "$SANDBOX/stub-state/netxml-isol-administration" "address='10.10.3.1'"
assert_contains "the guest agent channel is wired up (isolate.sh needs it)" "$STUB_LOG" 'target.name=org.qemu.guest_agent.0'
assert_not_contains "no shared filesystem device is ever created" "$STUB_LOG" '--filesystem'

# --- the generated cloud-init is valid YAML ----------------------------------
extract_userdata "$SANDBOX/images/office-seed.iso" "$SANDBOX/office-ud.yaml"
assert_ok "office seed: user-data is valid YAML" yaml_ok "$SANDBOX/office-ud.yaml"
extract_userdata "$SANDBOX/images/development-seed.iso" "$SANDBOX/dev-ud.yaml"
assert_ok "development seed: user-data is valid YAML" yaml_ok "$SANDBOX/dev-ud.yaml"
extract_userdata "$SANDBOX/images/administration-seed.iso" "$SANDBOX/adm-ud.yaml"
assert_ok "administration seed (DE=none): user-data is valid YAML" yaml_ok "$SANDBOX/adm-ud.yaml"

# --- the guest user is actually created --------------------------------------
assert_contains "the guest user is declared" "$SANDBOX/office-ud.yaml" '^  - name: operator$'
assert_not_contains "the user is created group-free (a bad group aborts useradd)" \
  "$SANDBOX/office-ud.yaml" '^    groups:'
assert_contains "the admin group is added afterwards, best-effort" "$SANDBOX/office-ud.yaml" 'usermod -aG sudo,adm operator'
assert_contains "arch guests get the wheel group" "$SANDBOX/dev-ud.yaml" 'usermod -aG wheel operator'
assert_contains "arch guests also get the sudo package (the image ships none)" "$SANDBOX/dev-ud.yaml" '^  - sudo$'
assert_contains "passwords are handed over as plaintext for cloud-init to hash" "$SANDBOX/office-ud.yaml" 'operator:testpw123'

# --- desktop environment per distro ------------------------------------------
assert_contains "ubuntu+gnome installs the ubuntu desktop and gdm3" "$SANDBOX/office-ud.yaml" 'ubuntu-desktop-minimal gdm3'
assert_contains "gdm3 gets an autologin drop-in" "$SANDBOX/office-ud.yaml" '/etc/gdm3/custom.conf'
assert_contains "arch+xfce4 installs via pacman" "$SANDBOX/dev-ud.yaml" 'pacman -Sy --noconfirm --needed xorg xfce4'
assert_contains "lightdm gets an autologin seat" "$SANDBOX/dev-ud.yaml" 'autologin-user=operator'
assert_contains "the DE install is a retrying service, not a one-shot runcmd" "$SANDBOX/office-ud.yaml" 'appliance-de.service'
assert_contains "the DE install reboots once into graphical.target" "$SANDBOX/office-ud.yaml" 'mode: reboot'
assert_not_contains "a DE=none env installs no desktop" "$SANDBOX/adm-ud.yaml" 'appliance-de.service'
assert_not_contains "a DE=none env does not reboot" "$SANDBOX/adm-ud.yaml" 'mode: reboot'

# --- the plaintext staging copy is gone --------------------------------------
if [ -f "$SANDBOX/cache/seed-office/user-data" ]; then
  _b "the plaintext user-data staging copy is shredded after the ISO is built"
else
  _g "the plaintext user-data staging copy is shredded after the ISO is built"
fi
assert_mode "the seed staging directory is root-only" 700 "$SANDBOX/cache/seed-office"

# --- idempotency + RECREATE ---------------------------------------------------
: > "$STUB_LOG"
"$SANDBOX/environments/create.sh" > "$SANDBOX/create2.out" 2>&1
assert_contains "a second run skips existing VMs" "$SANDBOX/create2.out" 'already exists — skipping'
assert_not_contains "a second run does not re-run virt-install" "$STUB_LOG" 'virt-install .*--name office '
: > "$STUB_LOG"
RECREATE=office "$SANDBOX/environments/create.sh" > "$SANDBOX/create3.out" 2>&1
assert_contains "RECREATE=<env> rebuilds only that env" "$STUB_LOG" 'virt-install .*--name office '
assert_not_contains "RECREATE=<env> leaves the others alone" "$STUB_LOG" 'virt-install .*--name development '

# --- supply-chain guards ------------------------------------------------------
new_sandbox
"$SANDBOX/environments/create.sh" > "$SANDBOX/nopin.out" 2>&1
assert_contains "an unpinned base image warns but proceeds by default" "$SANDBOX/nopin.out" 'no SHA256 pinned'
new_sandbox
cfg_set REQUIRE_IMG_SHA256 1
assert_fails "REQUIRE_IMG_SHA256=1 makes a missing pin a hard error" "$SANDBOX/environments/create.sh"
new_sandbox
cfg_set UBUNTU_IMG_SHA256 "0000000000000000000000000000000000000000000000000000000000000000"
"$SANDBOX/environments/create.sh" > "$SANDBOX/badsha.out" 2>&1
assert_contains "a mismatched pin aborts" "$SANDBOX/badsha.out" 'SHA256 MISMATCH'
if [ -f "$SANDBOX/images/base-ubuntu.img" ]; then
  _b "a mismatched image is deleted so it cannot be reused"
else
  _g "a mismatched image is deleted so it cannot be reused"
fi
new_sandbox
cfg_set office_INTUNE 1
cfg_set MS_GPG_FPR ""
assert_fails "a blanked Microsoft key fingerprint refuses to build the seed" \
  "$SANDBOX/environments/create.sh"
new_sandbox
cfg_set development_INTUNE 1     # arch env — Intune is Ubuntu-only
assert_fails "INTUNE=1 on a non-Ubuntu env is rejected" "$SANDBOX/environments/create.sh"

# --- integrations wire in correctly ------------------------------------------
new_sandbox
cfg_set office_INTUNE 1
cfg_set office_MSAPPS 1
cfg_set office_WAZUH 1
cfg_set WAZUH_MANAGER "wazuh.example.test"
cfg_set APT_MIRROR "http://mirror.example.test/ubuntu"
cfg_set APT_PROXY "http://10.10.1.1:3142"
"$SANDBOX/environments/create.sh" > "$SANDBOX/int.out" 2>&1
extract_userdata "$SANDBOX/images/office-seed.iso" "$SANDBOX/int-ud.yaml"
assert_ok "user-data with every integration on is still valid YAML" yaml_ok "$SANDBOX/int-ud.yaml"
assert_contains "the Microsoft key fingerprint is verified before use" "$SANDBOX/int-ud.yaml" 'BC528686B50D79E339D3721CEB3E94ADBE1229CF'
assert_contains "a key mismatch aborts the integration in-guest" "$SANDBOX/int-ud.yaml" 'fingerprint mismatch'
assert_contains "Teams is installed as an Edge PWA" "$SANDBOX/int-ud.yaml" 'teams.microsoft.com'
assert_contains "the Wazuh agent points at the configured manager" "$SANDBOX/int-ud.yaml" 'WAZUH_MANAGER=\\?"wazuh.example.test'
assert_contains "the apt proxy is applied globally" "$SANDBOX/int-ud.yaml" 'proxy: "http://10.10.1.1:3142"'
assert_contains "the apt primary mirror is rewritten" "$SANDBOX/int-ud.yaml" 'uri: "http://mirror.example.test/ubuntu"'
extract_userdata "$SANDBOX/images/development-seed.iso" "$SANDBOX/int-dev.yaml"
assert_not_contains "arch guests ignore the apt settings" "$SANDBOX/int-dev.yaml" 'apt:'

# --- vendor GPG signature verification of base images -------------------------
# These run REAL gpg (installed in the container) against a local "mirror":
# gpg_lab() installs a test-local wget (prepended to PATH) that serves files
# from $MIRROR by URL basename, so the signed-SHA256SUMS flow runs end to end
# without the network. A checksum/signature basename absent from the mirror
# fails the "download" (a genuinely missing file); anything else falls back to
# the fake-image behaviour of the stock stub.
gpg_lab() {
  new_sandbox
  MIRROR="$SANDBOX/mirror"; mkdir -p "$MIRROR"; export MIRROR
  cat > "$SANDBOX/wget" <<'EOF'
#!/bin/sh
: "${STUB_LOG:=/tmp/stub.log}"
printf 'wget %s\n' "$*" >> "$STUB_LOG"
out=""; prev=""; url=""
for a in "$@"; do [ "$prev" = "-O" ] && out="$a"; prev="$a"; url="$a"; done
[ -n "$out" ] || exit 1
base="$(basename "$url")"
if [ -f "$MIRROR/$base" ]; then cp "$MIRROR/$base" "$out"; exit 0; fi
case "$base" in SHA256SUMS*|sha256sums*) exit 1 ;; esac
qemu-img create -f qcow2 "$out" 64M >/dev/null 2>&1 || printf 'FAKE-IMAGE\n' > "$out"
EOF
  chmod +x "$SANDBOX/wget"
  PATH="$SANDBOX:$PATH"; export PATH
  GNUPGHOME="$SANDBOX/gnupg"; export GNUPGHOME
  mkdir -p "$GNUPGHOME"; chmod 700 "$GNUPGHOME"
  gpg --batch --pinentry-mode loopback --passphrase '' \
      --quick-gen-key 'Appliance Test Vendor <vendor@example.test>' ed25519 sign never >/dev/null 2>&1
  VENDOR_FPR="$(gpg --batch --with-colons -k vendor@example.test | awk -F: '/^fpr:/ {print $10; exit}')"
  gpg --batch --export vendor@example.test > "$SANDBOX/vendor-keyring.gpg" 2>/dev/null
}

# Publish a fake Ubuntu base image on the mirror; echo its real sha256. Must be
# a REAL qcow2: create_vm later uses it as a qemu-img backing file.
mirror_ubuntu_image() {
  qemu-img create -f qcow2 "$MIRROR/jammy-server-cloudimg-amd64.img" 64M >/dev/null 2>&1
  sha256sum "$MIRROR/jammy-server-cloudimg-amd64.img" | awk '{print $1}'
}
# Publish SHA256SUMS for that image, detached-signed by the given key uid.
mirror_ubuntu_sums() {
  printf '%s *jammy-server-cloudimg-amd64.img\n' \
    "$(sha256sum "$MIRROR/jammy-server-cloudimg-amd64.img" | awk '{print $1}')" > "$MIRROR/SHA256SUMS"
  gpg --batch --pinentry-mode loopback --passphrase '' -u "$1" \
      --detach-sign -o "$MIRROR/SHA256SUMS.gpg" "$MIRROR/SHA256SUMS" 2>/dev/null
}

# strict success — vendor key supplied out of band via IMG_GPG_KEYRING
gpg_lab
mirror_ubuntu_image >/dev/null
mirror_ubuntu_sums vendor@example.test
cfg_set UBUNTU_IMG_GPG_FPR "$VENDOR_FPR"
cfg_set IMG_GPG_KEYRING "$SANDBOX/vendor-keyring.gpg"
"$SANDBOX/environments/create.sh" > "$SANDBOX/gpg-ok.out" 2>&1
assert_eq "strict mode: a vendor-signed checksum file verifies" 0 "$?"
assert_contains "strict mode: the sums file is fetched from the image's own directory" "$STUB_LOG" 'wget .*jammy/current/SHA256SUMS$'
assert_contains "strict mode: the detached signature is fetched too" "$STUB_LOG" 'wget .*jammy/current/SHA256SUMS\.gpg'
assert_contains "strict mode: trust is gated on the pinned fingerprint" "$SANDBOX/gpg-ok.out" 'signature verified against pinned key'
assert_contains "strict mode: the image hash comes from the VERIFIED sums file" "$SANDBOX/gpg-ok.out" 'base-ubuntu.img: SHA256 verified'
: > "$STUB_LOG"
"$SANDBOX/environments/create.sh" > "$SANDBOX/gpg-cached.out" 2>&1
assert_eq "strict mode: a cached image still verifies on re-run" 0 "$?"
assert_contains "strict mode: the cached image is re-verified against a fresh signature fetch" "$STUB_LOG" 'SHA256SUMS\.gpg'

# a valid signature from the WRONG key must be refused — gpg exit 0 is not enough
gpg_lab
gpg --batch --pinentry-mode loopback --passphrase '' \
    --quick-gen-key 'Mallory <mallory@example.test>' ed25519 sign never >/dev/null 2>&1
gpg --batch --export mallory@example.test >> "$SANDBOX/vendor-keyring.gpg" 2>/dev/null
mirror_ubuntu_image >/dev/null
mirror_ubuntu_sums mallory@example.test
cfg_set UBUNTU_IMG_GPG_FPR "$VENDOR_FPR"
cfg_set IMG_GPG_KEYRING "$SANDBOX/vendor-keyring.gpg"
"$SANDBOX/environments/create.sh" > "$SANDBOX/gpg-wrong.out" 2>&1
if [ "$?" -ne 0 ]; then _g "a valid signature from the WRONG key is refused"; else _b "a valid signature from the WRONG key is refused"; fi
assert_contains "wrong key: the refusal names the pinned key" "$SANDBOX/gpg-wrong.out" 'not by the pinned key'
if [ -f "$SANDBOX/images/base-ubuntu.img" ]; then
  _b "wrong key: the image is deleted so it cannot be reused"
else
  _g "wrong key: the image is deleted so it cannot be reused"
fi

# a missing detached signature must be refused
gpg_lab
mirror_ubuntu_image >/dev/null
printf '%s *jammy-server-cloudimg-amd64.img\n' \
  "$(sha256sum "$MIRROR/jammy-server-cloudimg-amd64.img" | awk '{print $1}')" > "$MIRROR/SHA256SUMS"
cfg_set UBUNTU_IMG_GPG_FPR "$VENDOR_FPR"
cfg_set IMG_GPG_KEYRING "$SANDBOX/vendor-keyring.gpg"
"$SANDBOX/environments/create.sh" > "$SANDBOX/gpg-nosig.out" 2>&1
if [ "$?" -ne 0 ]; then _g "a missing detached signature is refused"; else _b "a missing detached signature is refused"; fi
assert_contains "missing signature: the refusal says why" "$SANDBOX/gpg-nosig.out" 'SHA256SUMS\.gpg missing'

# empty-but-set <OS>_IMG_GPG_FPR is a refused downgrade, not "feature off"
new_sandbox
cfg_set UBUNTU_IMG_GPG_FPR ""
"$SANDBOX/environments/create.sh" > "$SANDBOX/gpg-empty.out" 2>&1
if [ "$?" -ne 0 ]; then _g "an empty-but-set <OS>_IMG_GPG_FPR dies"; else _b "an empty-but-set <OS>_IMG_GPG_FPR dies"; fi
assert_contains "empty fpr: the message calls it a refused downgrade" "$SANDBOX/gpg-empty.out" 'refused downgrade'

# a hand-pinned SHA256 WINS over the signature path
gpg_lab
img_sha="$(mirror_ubuntu_image)"
# deliberately NO checksum/signature published — the signature path must not run
cfg_set UBUNTU_IMG_GPG_FPR "$VENDOR_FPR"
cfg_set IMG_GPG_KEYRING "$SANDBOX/vendor-keyring.gpg"
cfg_set UBUNTU_IMG_SHA256 "$img_sha"
"$SANDBOX/environments/create.sh" > "$SANDBOX/gpg-pin.out" 2>&1
assert_eq "a hand-pinned SHA256 wins over the signature path" 0 "$?"
assert_not_contains "pin precedence: the sums file is never fetched" "$STUB_LOG" 'SHA256SUMS'

# REQUIRE_IMG_SHA256=1 is satisfied by a gpg pin (no sha pin needed)
gpg_lab
mirror_ubuntu_image >/dev/null
mirror_ubuntu_sums vendor@example.test
# (the arch image must also be a real qcow2 — create_vm uses it as a backing file)
qemu-img create -f qcow2 "$MIRROR/Arch-Linux-x86_64-cloudimg.qcow2" 64M >/dev/null 2>&1
arch_sha="$(sha256sum "$MIRROR/Arch-Linux-x86_64-cloudimg.qcow2" | awk '{print $1}')"
cfg_set REQUIRE_IMG_SHA256 1
cfg_set UBUNTU_IMG_GPG_FPR "$VENDOR_FPR"   # gpg pin must satisfy REQUIRE_IMG_SHA256
cfg_set IMG_GPG_KEYRING "$SANDBOX/vendor-keyring.gpg"
cfg_set ARCH_IMG_SHA256 "$arch_sha"        # the arch envs pin a hash instead
"$SANDBOX/environments/create.sh" > "$SANDBOX/gpg-req.out" 2>&1
assert_eq "REQUIRE_IMG_SHA256=1 is satisfied by a gpg pin" 0 "$?"

summary
