#!/bin/bash
# =============================================================================
# 0host/switching.sh
# -----------------------------------------------------------------------------
# Write the i3 config that turns the appliance into a 3-VM kiosk:
#   * workspace 1 = desktop VM viewer   (boot lands here)
#   * workspace 2 = devops VM viewer
#   * workspace 3 = analysis VM viewer
#   * Super+1/2/3 switch instantly between them
#   * every viewer is fullscreen, no borders, no gaps -> you never see the host
#
# Each virt-viewer is launched with --kiosk so the guest owns the whole surface.
# i3 assigns each viewer window to its workspace by matching window class/title.
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=../lib/common.sh
. "$HERE/../lib/common.sh"
require_root
load_config

# The desktop runs as the unprivileged kiosk user, so write its i3/viewer config
# into the kiosk home (not /root).
KIOSK_USER="${KIOSK_USER:-kiosk}"
KIOSK_HOME="$(getent passwd "$KIOSK_USER" | cut -d: -f6)"; KIOSK_HOME="${KIOSK_HOME:-/home/$KIOSK_USER}"
I3_DIR="$KIOSK_HOME/.config/i3"
mkdir -p "$I3_DIR"

log "Writing $I3_DIR/config (per enabled environment) ..."
# Static header (quoted heredoc keeps i3 $vars literal).
cat > "$I3_DIR/config" <<'EOF'
# ===== VM-kiosk i3 config (generated by host/switching.sh) =====
set $mod Mod4
font pango:DejaVu Sans Mono 8
default_border none
default_floating_border none
hide_edge_borders both
focus_follows_mouse no

bindsym $mod+Tab workspace next
bindsym $mod+Shift+r restart
bindsym $mod+Shift+q kill
# Host terminal (X runs as root -> ROOT shell). Super+Return.
bindsym $mod+Return exec xterm
for_window [class="(?i)xterm"] floating enable, border normal
# Super+y = route a plugged YubiKey (or USB) to a chosen VM (manual fallback).
bindsym $mod+y exec --no-startup-id xterm -T "Route YubiKey" -e HOMEDIR_APP/host/usb-to-vm.sh
EOF
# Bake the real appliance path into the Super+y binding (header is a quoted heredoc).
sed -i "s|HOMEDIR_APP|$APP_ROOT|" "$I3_DIR/config"

# Per ENABLED env: title-match the viewer to its numbered workspace, bind
# Super+<idx>, and launch its viewer. Workspaces are named "<idx>: <ENV>" for the
# ANSSI trust bar. Switching uses `workspace number` so the label doesn't matter.
first_idx=""
for_each_enabled_env | while read -r env idx; do
  label="$(env_title "$env")"
  cat >> "$I3_DIR/config" <<EOF

# --- $env (workspace $idx) ---
for_window [class="(?i)virt-viewer" title="(?i)$env"] move to workspace "$idx: $label", border none
bindsym \$mod+$idx workspace number $idx
exec --no-startup-id sh -c 'exec ~/vm-viewer.sh $env'
EOF
done
# Land on the first enabled env at boot.
# NOTE: awk 'NR==1' (not '| head -1') — head closes the pipe early, which under
# 'set -o pipefail' makes for_each_enabled_env fail with SIGPIPE and aborts the
# whole script (that truncated the config: no trust bar, no vm-viewer, no keyd).
first_idx="$(for_each_enabled_env | awk 'NR==1{print $2}')"
echo "exec --no-startup-id i3-msg workspace number ${first_idx:-1}" >> "$I3_DIR/config"

# -----------------------------------------------------------------------------
# ANSSI barre de confiance + fullscreen mode (TRUST_BAR).
#  TRUST_BAR=1 (default, ANSSI): a colored bar is ALWAYS visible showing which
#    environment is active; viewers tile below it (not fullscreen), so the bar
#    can never be hidden by a guest.
#  TRUST_BAR=0: guests go true fullscreen (edge-to-edge), no persistent bar.
# -----------------------------------------------------------------------------
: "${TRUST_BAR:=1}"
if [ "$TRUST_BAR" = "1" ]; then
  VIEWER_FS=""     # virt-viewer NOT --full-screen -> i3 tiles it below the bar
  cat >> "$I3_DIR/config" <<'EOF'

# --- Trust bar: always-visible active-environment indicator (ANSSI) ----------
# Distinct strong color per env so the user can never mistake which one is live.
# Viewers are NOT fullscreen, so this dock bar is always on top.
bar {
    position top
    mode dock
    workspace_buttons yes
    status_command i3status
    font pango:DejaVu Sans Mono 11
    colors {
        background #000000
        statusline #ffffff
        # focused workspace = the ACTIVE environment, shown big and bright.
        focused_workspace  #ffffff #007000 #ffffff
        active_workspace   #000000 #333333 #ffffff
        inactive_workspace #000000 #111111 #888888
        urgent_workspace   #000000 #900000 #ffffff
    }
}
EOF
else
  VIEWER_FS="--full-screen"
  cat >> "$I3_DIR/config" <<'EOF'

# TRUST_BAR=0: guests fullscreen, no persistent bar.
for_window [class="(?i)virt-viewer"] fullscreen enable, border none
EOF
fi
# vm-viewer.sh reads this to decide fullscreen vs windowed (below the trust bar).
echo "$VIEWER_FS" > "$KIOSK_HOME/.vm-viewer-fs"

# -----------------------------------------------------------------------------
# Watchdog launcher: keeps each viewer alive and correctly titled. If a guest
# reboots or the viewer dies, this respawns it so the kiosk never shows the WM
# background (i.e. never "shows the host").
# -----------------------------------------------------------------------------
log "Writing $KIOSK_HOME/vm-viewer.sh (respawning full-screen launcher) ..."
# NOTE: --full-screen, NOT --kiosk. --kiosk takes a full keyboard grab via SPICE
# so i3's Super+1/2/3 never reach the WM (can't switch VMs). --full-screen lets
# i3 manage/switch the windows. i3 forces fullscreen+no-border (see above), so
# the guest still fills the screen edge-to-edge.
cat > "$KIOSK_HOME/vm-viewer.sh" <<'EOF'
#!/bin/sh
# vm-viewer.sh <domain> — keep a virt-viewer attached to <domain>. Runs as the
# kiosk user (i3 exec), so $HOME is the kiosk home.
# FS = "--full-screen" (TRUST_BAR=0) or "" (TRUST_BAR=1, tiled below trust bar),
# written by host/switching.sh into ~/.vm-viewer-fs.
vm="$1"
FS="$(cat "$HOME/.vm-viewer-fs" 2>/dev/null || echo --full-screen)"
while true; do
  # NOTE: no --title (this virt-viewer build rejects it). The window title comes
  # from the domain name, which the i3 for_window rules match on.
  # SPICE grabs the keyboard while the guest is focused, so i3's Super hotkeys are
  # eaten. keyd (evdev, below X) handles switching; Ctrl+Alt also releases the grab.
  virt-viewer \
    --connect qemu:///system \
    $FS \
    --hotkeys=release-cursor=ctrl+alt,toggle-fullscreen=shift+f11 \
    --wait \
    --reconnect \
    --attach "$vm" \
    2>/tmp/viewer-$vm.log
  # If the viewer exits (guest off / disconnect), wait then relaunch.
  sleep 2
done
EOF
chmod +x "$KIOSK_HOME/vm-viewer.sh"
# Own all kiosk desktop config (i3, viewer, fs flag) by the kiosk user.
chown -R "$KIOSK_USER:$KIOSK_USER" "$KIOSK_HOME/.config" "$KIOSK_HOME/vm-viewer.sh" "$KIOSK_HOME/.vm-viewer-fs" 2>/dev/null || true

# -----------------------------------------------------------------------------
# SEAMLESS SWITCHING under the SPICE keyboard grab.
# SPICE grabs the X keyboard while a guest is focused, so i3's Super+<n> never
# fire. keyd reads the keyboard at the KERNEL/evdev layer (BELOW X), so it sees
# the chord even while SPICE holds the X grab, and runs i3-msg — no release dance.
# -----------------------------------------------------------------------------
log "Writing /usr/local/bin/vmswitch + keyd hotkeys ..."
mkdir -p /usr/local/bin /etc/keyd
# keyd runs vmswitch as ROOT; point it at the kiosk user's X session so i3-msg
# reaches the kiosk's i3 (unquoted heredoc bakes the kiosk home; \$1 stays literal).
cat > /usr/local/bin/vmswitch <<EOF
#!/bin/sh
# Called by keyd on a global hotkey. Talks to the kiosk user's i3 on :0.
export DISPLAY=:0
export XAUTHORITY="$KIOSK_HOME/.Xauthority"
case "\$1" in
  term) i3-msg exec xterm ;;
  *)    i3-msg workspace number "\$1" ;;
esac
EOF
chmod +x /usr/local/bin/vmswitch

# Generate keyd bindings: meta+<idx> -> switch to that env's workspace, for every
# ENABLED env. command() fires below X (works under the SPICE grab) and swallows
# the chord. meta+enter = host shell.
{
  echo "[ids]"; echo "*"; echo; echo "[main]"
  for_each_enabled_env | while read -r env idx; do
    echo "meta+$idx = command(/usr/local/bin/vmswitch $idx)"
  done
  echo "meta+enter = command(/usr/local/bin/vmswitch term)"
} > /etc/keyd/default.conf

# Enable keyd (idempotent).
if command -v rc-update >/dev/null 2>&1; then
  rc-update add keyd default 2>/dev/null || true
  rc-service keyd restart 2>/dev/null || rc-service keyd start 2>/dev/null || true
elif command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now keyd 2>/dev/null || true
fi

ok "Switching configured for enabled envs: $(for_each_enabled_env | awk '{printf "%s(Super+%s) ",$1,$2}'). Super+Enter = host shell."
cat <<EOF

Next: ./environments/isolate.sh
EOF
