#!/bin/bash
# =============================================================================
# host/switching.sh
# -----------------------------------------------------------------------------
# Write the i3 config that turns the appliance into a 3-VM kiosk:
#   * workspace 1 = desktop VM viewer   (boot lands here)
#   * workspace 2 = devops VM viewer
#   * workspace 3 = analysis VM viewer
#   * Super+1/2/3 switch instantly between them
#   * every viewer is fullscreen, no borders, no gaps -> you never see the host
#
# Each virt-viewer is launched with --kiosk so the guest owns the whole surface.
# i3 assigns each viewer window to its workspace by matching window class/title.
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=../lib/common.sh
. "$HERE/../lib/common.sh"
require_root
load_config

# The desktop runs as the unprivileged kiosk user, so write its i3/viewer config
# into the kiosk home (not /root).
KIOSK_USER="${KIOSK_USER:-kiosk}"
KIOSK_HOME="$(getent passwd "$KIOSK_USER" | cut -d: -f6)"; KIOSK_HOME="${KIOSK_HOME:-/home/$KIOSK_USER}"
I3_DIR="$KIOSK_HOME/.config/i3"
mkdir -p "$I3_DIR"
# Captive-portal helper (written by host/captive-portal.sh into the kiosk home).
# vmswitch launches it under the SPICE grab via keyd (below).
PORTAL_SH="$KIOSK_HOME/portal-login.sh"
# Dedicated workspaces for overlays so they are NOT hidden behind a fullscreen VM.
WS_PORTAL=8
WS_SHELL=9

log "Writing $I3_DIR/config (per enabled environment) ..."
# Static header (quoted heredoc keeps i3 $vars literal).
cat > "$I3_DIR/config" <<'EOF'
# ===== VM-kiosk i3 config (generated by host/switching.sh) =====
set $mod Mod4
font pango:DejaVu Sans Mono 8
default_border none
default_floating_border none
hide_edge_borders both
focus_follows_mouse no

bindsym $mod+Tab workspace next
bindsym $mod+Shift+r restart
bindsym $mod+Shift+q kill
# Terminal on a dedicated workspace so it's not hidden behind a fullscreen VM.
# NOTE: X/i3 run as the unprivileged kiosk user, so this is a KIOSK shell, not
# root. Root admin lives on tty2 (Ctrl+Alt+F2). Super+Return.
bindsym $mod+Return workspace number 9; exec xterm
for_window [class="(?i)xterm"] floating enable, border normal
# Super+y = route a plugged YubiKey (or USB) to a chosen VM (manual fallback).
bindsym $mod+y exec --no-startup-id xterm -T "Route YubiKey" -e HOMEDIR_APP/host/usb-to-vm.sh
EOF
# Bake the real appliance path into the Super+y binding (header is a quoted heredoc).
sed -i "s|HOMEDIR_APP|$APP_ROOT|" "$I3_DIR/config"

# Per ENABLED env: title-match the viewer to its numbered workspace, bind
# Super+<idx>, and launch its viewer. Workspaces are named "<idx>: <ENV>" for the
# ANSSI trust bar. Switching uses `workspace number` so the label doesn't matter.
first_idx=""
for_each_enabled_env | while read -r env idx; do
  label="$(env_title "$env")"
  cat >> "$I3_DIR/config" <<EOF

# --- $env (workspace $idx) ---
for_window [class="(?i)virt-viewer" title="(?i)$env"] move to workspace "$idx: $label", border none
bindsym \$mod+$idx workspace number $idx
exec --no-startup-id sh -c 'exec ~/vm-viewer.sh $env'
EOF
done
# Land on the first enabled env at boot.
# NOTE: awk 'NR==1' (not '| head -1') — head closes the pipe early, which under
# 'set -o pipefail' makes for_each_enabled_env fail with SIGPIPE and aborts the
# whole script (that truncated the config: no trust bar, no vm-viewer, no keyd).
first_idx="$(for_each_enabled_env | awk 'NR==1{print $2}')"
echo "exec --no-startup-id i3-msg workspace number ${first_idx:-1}" >> "$I3_DIR/config"

# -----------------------------------------------------------------------------
# ANSSI barre de confiance + fullscreen mode (TRUST_BAR).
#  TRUST_BAR=1 (default, ANSSI): a colored bar is ALWAYS visible showing which
#    environment is active; viewers tile below it (not fullscreen), so the bar
#    can never be hidden by a guest.
#  TRUST_BAR=0: guests go true fullscreen (edge-to-edge), no persistent bar.
# -----------------------------------------------------------------------------
: "${TRUST_BAR:=1}"
PB_DIR="$KIOSK_HOME/.config/polybar"
if [ "$TRUST_BAR" = "1" ]; then
  # Viewers go true --full-screen (no virt-viewer toolbar/menu chrome); the thin
  # polybar is override-redirect so it stays painted ON TOP of the fullscreen VM.
  VIEWER_FS="--full-screen"
  log "Writing custom polybar trust bar into $PB_DIR ..."
  cat >> "$I3_DIR/config" <<EOF

# --- Trust bar: custom polybar (ANSSI always-visible active-env indicator) ---
# polybar reserves the top strut, so viewers tile below it and can't hide it.
exec_always --no-startup-id $PB_DIR/launch.sh
EOF
  mkdir -p "$PB_DIR"

  # Build per-env name/color lookups. Workspace number == env index, so the bar
  # can color itself from the focused workspace alone. Palette cycles if there
  # are more envs than colors. Strong, distinct hues: blue/green/red/amber/...
  palette="#3b82f6 #22c55e #ef4444 #f59e0b #a855f7 #06b6d4 #ec4899"
  name_cases=""; color_cases=""; all_idx=""
  while read -r _env _idx; do
    [ -n "$_env" ] || continue
    _lbl="$(env_title "$_env")"
    _col="$(echo "$palette" | awk -v n="$_idx" '{print $(((n-1)%NF)+1)}')"
    [ -n "$_col" ] || _col="#3b82f6"
    name_cases="${name_cases}    $_idx) printf '%s' '$_lbl' ;;
"
    color_cases="${color_cases}    $_idx) printf '%s' '$_col' ;;
"
    all_idx="$all_idx $_idx"
  done <<EOF
$(for_each_enabled_env)
EOF

  # Label the overlay workspaces too (Super+p portal = $WS_PORTAL, Super+Return
  # shell = $WS_SHELL) so the trust bar shows what you're looking at there.
  name_cases="${name_cases}    $WS_PORTAL) printf '%s' 'PORTAL' ;;
    $WS_SHELL) printf '%s' 'SHELL' ;;
"
  color_cases="${color_cases}    $WS_PORTAL) printf '%s' '#f59e0b' ;;
    $WS_SHELL) printf '%s' '#6b6b6b' ;;
"

  # active-env.sh: the left module. A rounded colored "pill" with the ACTIVE env
  # name (recolors live on switch) + one dot per env. Renders via i3 events, so
  # it needs no polybar-i3 support (just i3-msg + jq). Header (lookups) is an
  # expanding heredoc; the render logic below is a quoted heredoc (kept literal).
  cat > "$PB_DIR/active-env.sh" <<EOF
#!/bin/sh
# Generated by host/switching.sh — do not edit.
name_of(){ case "\$1" in
$name_cases    *) printf 'ENV' ;;
  esac; }
color_of(){ case "\$1" in
$color_cases    *) printf '#3b82f6' ;;
  esac; }
ALL_IDX="$all_idx"
EOF
  cat >> "$PB_DIR/active-env.sh" <<'EOF'
render(){
  n="$(i3-msg -t get_workspaces 2>/dev/null | jq -r '.[]|select(.focused).num' 2>/dev/null)"
  [ -n "$n" ] || n=1
  c="$(color_of "$n")"; nm="$(name_of "$n")"
  cap_l="%{T2}%{F${c}}%{T-}"                              # left rounded cap
  cap_r="%{T2}%{F${c}}%{T-}"                              # right rounded cap
  pill="${cap_l}%{B${c}}%{F#0d0d0f}  ${nm}  %{F-}%{B-}${cap_r}"
  dots=""
  for i in $ALL_IDX; do
    ci="$(color_of "$i")"
    if [ "$i" = "$n" ]; then dots="${dots}  %{F${ci}}%{F-}"
    else dots="${dots}  %{F#3a3a3a}%{F-}"; fi
  done
  printf '%s    %s   \n' "$pill" "$dots"
}
render
i3-msg -t subscribe -m '[ "workspace" ]' 2>/dev/null | while read -r _ev; do render; done
EOF

  # Right-side modules (custom scripts -> no hardcoded interface/battery names).
  cat > "$PB_DIR/net.sh" <<'EOF'
#!/bin/sh
i="$(ip route show default 2>/dev/null | awk '{print $5; exit}')"
[ -n "$i" ] || { echo "%{F#ef4444} offline%{F-}"; exit 0; }
echo "%{F#8ab4f8}%{F-} $i"
EOF
  cat > "$PB_DIR/vpn.sh" <<'EOF'
#!/bin/sh
if ip -o link show 2>/dev/null | grep -qE ': wg[0-9]'; then
  echo "%{F#22c55e} vpn%{F-}"
else
  echo "%{F#4a4a4a} vpn%{F-}"
fi
EOF
  cat > "$PB_DIR/battery.sh" <<'EOF'
#!/bin/sh
cap="$(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null | head -1)"
[ -n "$cap" ] || exit 0
ac="$(cat /sys/class/power_supply/A*/online 2>/dev/null | head -1)"
ic=""; [ "$ac" = "1" ] && ic=""
echo "%{F#e8e8ea}$ic ${cap}%%{F-}"
EOF

  # polybar bar definition.
  cat > "$PB_DIR/config.ini" <<'EOF'
[colors]
bg  = #0d0d0f
fg  = #e8e8ea
mut = #6b6b6b

[bar/trust]
width  = 100%
height = 18
radius = 0
background = ${colors.bg}
foreground = ${colors.fg}
; font-0 = normal text/icons, font-1 = big glyphs for the rounded pill caps
font-0 = JetBrainsMono Nerd Font:size=8;2
font-1 = JetBrainsMono Nerd Font:size=11;3
padding-left  = 1
padding-right = 2
module-margin = 2
modules-left  = env
modules-right = cpu memory net vpn battery date
; override-redirect = the thin bar stays ON TOP of the fullscreen VM viewers.
; wm-restack=i3 (NOT generic) is what actually restacks polybar above an
; i3-fullscreen window — with 'generic' the fullscreen VM viewer covered the bar
; and it was never visible.
override-redirect = true
wm-restack = i3
enable-ipc = true

[module/env]
type = custom/script
exec = ~/.config/polybar/active-env.sh
tail = true

[module/cpu]
type = internal/cpu
interval = 2
label = %{F#f0a45d}%{F-} %percentage%%

[module/memory]
type = internal/memory
interval = 3
label = %{F#c9a0ff}%{F-} %percentage_used%%

[module/net]
type = custom/script
exec = ~/.config/polybar/net.sh
interval = 3

[module/vpn]
type = custom/script
exec = ~/.config/polybar/vpn.sh
interval = 3

[module/battery]
type = custom/script
exec = ~/.config/polybar/battery.sh
interval = 15

[module/date]
type = internal/date
interval = 5
date = %a %d %b
time = %H:%M
label = %{F#8ab4f8}%{F-} %date%  %time%
EOF

  # launch.sh: (re)start polybar cleanly on every i3 (re)start.
  cat > "$PB_DIR/launch.sh" <<'EOF'
#!/bin/sh
pkill -x polybar 2>/dev/null
for _ in 1 2 3 4 5; do pgrep -x polybar >/dev/null || break; sleep 0.2; done
polybar -q -c "$HOME/.config/polybar/config.ini" trust >/tmp/polybar.log 2>&1 &
EOF

  chmod +x "$PB_DIR"/*.sh
else
  VIEWER_FS="--full-screen"
  cat >> "$I3_DIR/config" <<'EOF'

# TRUST_BAR=0: guests fullscreen, no persistent bar.
for_window [class="(?i)virt-viewer"] fullscreen enable, border none
EOF
fi
# vm-viewer.sh reads this to decide fullscreen vs windowed (below the trust bar).
echo "$VIEWER_FS" > "$KIOSK_HOME/.vm-viewer-fs"

# -----------------------------------------------------------------------------
# Watchdog launcher: keeps each viewer alive and correctly titled. If a guest
# reboots or the viewer dies, this respawns it so the kiosk never shows the WM
# background (i.e. never "shows the host").
# -----------------------------------------------------------------------------
log "Writing $KIOSK_HOME/vm-viewer.sh (respawning full-screen launcher) ..."
# NOTE: --full-screen, NOT --kiosk. --kiosk takes a full keyboard grab via SPICE
# so i3's Super+1/2/3 never reach the WM (can't switch VMs). --full-screen lets
# i3 manage/switch the windows. i3 forces fullscreen+no-border (see above), so
# the guest still fills the screen edge-to-edge.
cat > "$KIOSK_HOME/vm-viewer.sh" <<'EOF'
#!/bin/sh
# vm-viewer.sh <domain> — keep a virt-viewer attached to <domain>. Runs as the
# kiosk user (i3 exec), so $HOME is the kiosk home.
# FS = "--full-screen" (TRUST_BAR=0) or "" (TRUST_BAR=1, tiled below trust bar),
# written by host/switching.sh into ~/.vm-viewer-fs.
vm="$1"
FS="$(cat "$HOME/.vm-viewer-fs" 2>/dev/null || echo --full-screen)"
while true; do
  # NOTE: no --title (this virt-viewer build rejects it). The window title comes
  # from the domain name, which the i3 for_window rules match on.
  # SPICE grabs the keyboard while the guest is focused, so i3's Super hotkeys are
  # eaten. keyd (evdev, below X) handles switching; Ctrl+Alt also releases the grab.
  virt-viewer \
    --connect qemu:///system \
    $FS \
    --hotkeys=release-cursor=ctrl+alt,toggle-fullscreen=shift+f11 \
    --wait \
    --reconnect \
    --attach "$vm" \
    2>/tmp/viewer-$vm.log
  # If the viewer exits (guest off / disconnect), wait then relaunch.
  sleep 2
done
EOF
chmod +x "$KIOSK_HOME/vm-viewer.sh"
# Own all kiosk desktop config (i3, viewer, fs flag) by the kiosk user.
chown -R "$KIOSK_USER:$KIOSK_USER" "$KIOSK_HOME/.config" "$KIOSK_HOME/vm-viewer.sh" "$KIOSK_HOME/.vm-viewer-fs" 2>/dev/null || true

# -----------------------------------------------------------------------------
# SEAMLESS SWITCHING under the SPICE keyboard grab.
# SPICE grabs the X keyboard while a guest is focused, so i3's Super+<n> never
# fire. keyd reads the keyboard at the KERNEL/evdev layer (BELOW X), so it sees
# the chord even while SPICE holds the X grab, and runs i3-msg — no release dance.
# -----------------------------------------------------------------------------
log "Writing /usr/local/bin/vmswitch + keyd hotkeys ..."
mkdir -p /usr/local/bin /etc/keyd
# keyd runs vmswitch as ROOT; point it at the kiosk user's X session so i3-msg
# reaches the kiosk's i3 (unquoted heredoc bakes the kiosk home; \$1 stays literal).
cat > /usr/local/bin/vmswitch <<EOF
#!/bin/sh
export PATH=/usr/local/bin:/usr/bin:/bin
# Called by keyd (as ROOT) on a global hotkey. Talks to the kiosk user's i3.
# CRITICAL: startx often puts the X cookie in ~/.serverauth.NNNN, NOT
# ~/.Xauthority — a hardcoded path makes i3-msg fail auth and switching does
# nothing. So read the REAL DISPLAY + XAUTHORITY from the running i3 process env.
KU="$KIOSK_USER"
pid="\$(pgrep -u "\$KU" -x i3 | head -1)"
if [ -n "\$pid" ] && [ -r "/proc/\$pid/environ" ]; then
  DISPLAY="\$(tr '\0' '\n' < "/proc/\$pid/environ" | sed -n 's/^DISPLAY=//p'    | head -1)"
  XAUTHORITY="\$(tr '\0' '\n' < "/proc/\$pid/environ" | sed -n 's/^XAUTHORITY=//p' | head -1)"
fi
: "\${DISPLAY:=:0}"
[ -n "\$XAUTHORITY" ] || XAUTHORITY="\$(ls "\$(getent passwd "\$KU" | cut -d: -f6)"/.Xauthority "\$(getent passwd "\$KU" | cut -d: -f6)"/.serverauth.* 2>/dev/null | head -1)"
export DISPLAY XAUTHORITY
# term/portal switch to a dedicated EMPTY workspace first, then exec — otherwise
# the xterm/browser opens behind the focused VM's fullscreen window and is never
# seen. Switching away also drops SPICE's keyboard grab, so normal keys work there.
case "\$1" in
  term)   i3-msg "workspace number $WS_SHELL; exec xterm" ;;
  portal) i3-msg "workspace number $WS_PORTAL; exec $PORTAL_SH" ;;
  *)      i3-msg workspace number "\$1" ;;
esac
EOF
chmod +x /usr/local/bin/vmswitch

# Generate keyd bindings: meta+<idx> -> switch to that env's workspace, for every
# ENABLED env. command() fires below X (works under the SPICE grab) and swallows
# the chord. meta+enter = host shell.
{
  echo "[ids]"; echo "*"; echo; echo "[main]"
  for_each_enabled_env | while read -r env idx; do
    echo "meta+$idx = command(/usr/local/bin/vmswitch $idx)"
  done
  echo "meta+enter = command(/usr/local/bin/vmswitch term)"
  # Super+p (captive-portal login) must also work UNDER the SPICE grab, so route
  # it through keyd like the workspace keys — an i3-only bindsym never fires while
  # a guest holds the keyboard grab.
  echo "meta+p = command(/usr/local/bin/vmswitch portal)"
} > /etc/keyd/default.conf

# Enable keyd (idempotent).
if command -v rc-update >/dev/null 2>&1; then
  rc-update add keyd default 2>/dev/null || true
  rc-service keyd restart 2>/dev/null || rc-service keyd start 2>/dev/null || true
elif command -v systemctl >/dev/null 2>&1; then
  systemctl enable --now keyd 2>/dev/null || true
fi

ok "Switching configured for enabled envs: $(for_each_enabled_env | awk '{printf "%s(Super+%s) ",$1,$2}'). Super+Enter = host shell."
cat <<EOF

Next (operator): create + isolate the VMs -> cd /opt/appliance && ./setup.sh
EOF
